//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeFinanse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incomes_by_category
    {
        public string CategoryName { get; set; }
        public Nullable<decimal> Incomes_total { get; set; }
        public string PeriodName { get; set; }
        public decimal Value { get; set; }
    }
}
