//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeFinanse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Summary
    {
        public int SummaryID { get; set; }
        public int PeriodID { get; set; }
        public Nullable<decimal> OnAccount { get; set; }
        public Nullable<decimal> ShouldBe { get; set; }
        public Nullable<decimal> Difference { get; set; }
        public Nullable<decimal> PerMonth { get; set; }
    
        public virtual Period Period { get; set; }
    }
}
